# Generated by Django 3.2 on 2021-05-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0002_auto_20210505_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
