# Generated by Django 3.2 on 2021-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0003_auto_20210505_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
