# Generated by Django 3.2 on 2021-05-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0005_block_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hybrid_app.document'),
        ),
    ]
