# Generated by Django 3.2 on 2021-05-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0006_alter_block_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='Untitled document', max_length=100),
        ),
    ]
