# Generated by Django 3.2 on 2021-05-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0007_auto_20210509_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
