# Generated by Django 3.2 on 2021-05-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0008_auto_20210509_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
