# Generated by Django 3.2 on 2021-05-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0011_alter_block_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hybrid_app/images/'),
        ),
    ]
