# Generated by Django 3.2 on 2021-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0012_alter_block_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='edit',
        ),
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
