# Generated by Django 3.2 on 2021-06-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0015_remove_block_equation_ascii'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='equation_latex',
            new_name='equation',
        ),
    ]
