# Generated by Django 3.2 on 2021-06-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0016_rename_equation_latex_block_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='next_block',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
