# Generated by Django 3.2 on 2021-06-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0017_block_next_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='next_block',
            new_name='next_block_pk',
        ),
    ]
