# Generated by Django 3.2 on 2021-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0018_rename_next_block_block_next_block_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='max_block_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
