# Generated by Django 3.2 on 2021-06-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0021_block_min_block_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='min_block_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
