# Generated by Django 3.2 on 2021-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0023_student_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='hybrid_app.Student'),
        ),
    ]
