# Generated by Django 3.2 on 2021-06-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0025_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(to='hybrid_app.StudentList'),
        ),
    ]
