# Generated by Django 3.2 on 2021-06-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0026_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hybrid_app.document'),
        ),
    ]
