# Generated by Django 3.2 on 2021-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0027_document_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matched',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='matched',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
