# Generated by Django 3.2 on 2021-10-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0029_rename_shared_with_document_shared_with_student_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with_students',
            field=models.ManyToManyField(to='hybrid_app.Student'),
        ),
    ]
