# Generated by Django 3.2 on 2021-10-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0030_document_shared_with_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='shared_with_student_lists',
            field=models.ManyToManyField(blank=True, null=True, to='hybrid_app.StudentList'),
        ),
        migrations.AlterField(
            model_name='document',
            name='shared_with_students',
            field=models.ManyToManyField(blank=True, null=True, to='hybrid_app.Student'),
        ),
    ]
