# Generated by Django 3.2 on 2021-10-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_app', '0031_auto_20211012_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with_teachers',
            field=models.ManyToManyField(blank=True, null=True, to='hybrid_app.Teacher'),
        ),
    ]
